openapi: 3.0.0
info:
  title: API service
  version: 1.0.0
paths:
  /v1:
    get:
      tags:
        - V1-Welcome
      summary: Welcome Message
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              example: Welcome to V1 Apis
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
              example:
                success: false
                message: Your session expired. Please login again.
                data: null
                error: null
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
              example:
                success: false
                message: 'ValidationError: "perPageRecords" is not allowed to be empty'
                data: null
                error: null
